### ISSUE TITLE
Q: can your wrapper handle restricted access

### ISSUE THREAD

**Issue by kingjr** [ygidtu/NBIA_data_retriever_CLI#1]
Hi,

Thanks for this package. Can it handle the downloading of restricted data. The official interface pops up a login window, but I don't see where we could parametrize this in your package.

Thank you

**Comment by ygidtu** [comment]
Sorry for the late response, this program cannot process the data with restricted data, cause I don't have account for testing. The open source data is all I need when I wrote this code.

**Comment by kingjr** [comment]
thank you
