### ISSUE TITLE
Update needed for Restricted Data

### ISSUE THREAD

**Issue by pka420** [ygidtu/NBIA_data_retriever_CLI#11]
Hi, 

I know that you did not test the server for restricted data, 
But, I have a account with TCIA, which I can use to confirm if we can download the restricted data. 
My question is can I work on the updates? 

When I try to download the restricted data this happens:
```bash
➜  NBIA_data_retriever_CLI git:(master) ✗ ./nbia_cli_darwin -i manifest_test2.tcia -o test2/ -p 1 -u username -w password
2023-11-29T16:27:49+05:30 | INFO   | Getting https://public.cancerimagingarchive.net/nbia-download/servlet/DownloadServletV3?numberOfSeries=1&series1=1.3.6.1.4.1.14519.5.2.1.4219.6651.146136900202431607373455344501
2023-11-29T16:27:51+05:30 | WARN   | [<!doctype html><html lang="en"><head><title>HTTP Status 460 – Unknown Reason</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 460 – Unknown Reason</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Login needed.</p><p><b>Description</b> No description available</p><hr class="line" /><h3>Apache Tomcat/9.0.80</h3></body></html>]
2023-11-29T16:27:51+05:30 | ERROR  | [<!doctype html><html lang="en"><head><title>HTTP Status 460 – Unknown Reason</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 460 – Unknown Reason</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Login needed.</p><p><b>Description</b> No description available</p><hr class="line" /><h3>Apache Tomcat/9.0.80</h3></body></html>] less than 11 elements
panic: runtime error: index out of range [1] with length 1
goroutine 20 [running]:
main.(*FileInfo).Get(0xc000176090)
        /Users/lucifer/projects/NBIA_data_retriever_CLI/download.go:62 +0x64c
main.main.func1(0x0?)
        /Users/lucifer/projects/NBIA_data_retriever_CLI/main.go:105 +0xaa
created by main.main in goroutine 1
        /Users/lucifer/projects/NBIA_data_retriever_CLI/main.go:102 +0x1e5
```

I suspect this is because the rest server from NBIA TCIA, is updated. https://wiki.cancerimagingarchive.net/display/Public/NBIA+Advanced+REST+API+Guide

Thank you!

**Comment by ygidtu** [comment]
Hi,
   I carefully reviewed the link you provided, and it seems that the official website offers a formal APIs to download data. I'll try to update a new version to download data through these APIs.
Best

**Comment by pka420** [comment]
Sounds good.
I am happy to help if you want to divide some work.

**Comment by ygidtu** [comment]
Hi, 
I investigate the official APIs, it seems they only provide search and metadata retrieve related functions, and the source code of NBIA-data-retriever did not change.
Therefore I suspect the  userId and password required to download the control data may recorded in somewhere else, such as the tcia file? 
Could you please compare your tcia file of controlled data and open data, see if there are userId and password filed?
Otherwise I could not make more updates now.
Best

**Comment by pka420** [comment]
Hi, sorry for the late reply. 
For limited/restricted data, I have the same tcia file as for public data:

```bash
downloadServerUrl=https://nbia.cancerimagingarchive.net/nbia-download/servlet/DownloadServlet
includeAnnotation=true
noOfrRetry=4
databasketId=manifest-1685648397515.tcia
manifestVersion=3.0
ListOfSeriesToDownload=
...seriesInstanceUIDS....
```

**Comment by pka420** [comment]
I also ran a test on postman, 

Basically logged in with the credentials here: `https://services.cancerimagingarchive.net/nbia-api/oauth/token`
This gave me an access_token and a refresh_token

The downloaded restricted data using this api: `https://services.cancerimagingarchive.net/nbia-api/services/v2/getImage?SeriesInstanceUID=`,` using access_token as authorization header for this request.

Example here: https://wiki.cancerimagingarchive.net/display/Public/NBIA+Search+with+Authentication+REST+API+Guide#NBIASearchwithAuthenticationRESTAPIGuide-getImage

**Comment by ygidtu** [comment]
> I also ran a test on postman, 
> 
> Basically logged in with the credentials here: `https://services.cancerimagingarchive.net/nbia-api/oauth/token`
> This gave me an access_token and a refresh_token
> 
> The downloaded restricted data using this api: `https://services.cancerimagingarchive.net/nbia-api/services/v2/getImage?SeriesInstanceUID=`,` using access_token as authorization header for this request.
> 
> Example here: https://wiki.cancerimagingarchive.net/display/Public/NBIA+Search+with+Authentication+REST+API+Guide#NBIASearchwithAuthenticationRESTAPIGuide-getImage

I'll do a little more research on this, thanks for your help

**Comment by ygidtu** [comment]
Hi,
    I write a new version of this tool, which using official APIs to download  image and metadata, please try with following code

    ```bash
    git clone git@github.com:ygidtu/NBIA_data_retriever_CLI.git
    cd NBIA_data_retriever_CLI
    git checkout dev
    go mod tidy
    go run . --help
    ```
    Please check whether this could access the controlled data.
Best

**Comment by pka420** [comment]
Hey @ygidtu 

I tried it, 
It created a `token.json` file in the output directory that contains the tokens.

The data did not get downloaded but I just got a bunch of binary data output on terminal.

**Comment by ygidtu** [comment]
Hi,
  Any example logs? And please try this public tcia file, it works with me. I wonder if this works universal.
  Please unzip the attached file and just run:
  ```bash
  go run . -i CMB-AML_October-2023-manifest.tcia -o ./
  ```
Best
[CMB-AML_October-2023-manifest.tcia.zip](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/13806615/CMB-AML_October-2023-manifest.tcia.zip)

**Comment by pka420** [comment]
Again, same problem, the data downloaded is displaying on the terminal as binary. 
token.json file is created.
Its not saving the downloaded data in the output directory.

**Comment by ygidtu** [comment]
Hi,
   I build several binaries for most common platform and architectures, due to I don't know what your machine is. Please try again with these binaries. I suspect you're facing building issue, could you please provide a screenshot or just the printed log in your console, if there are still errors.
Best
[binaries.zip](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/13815321/binaries.zip)

**Comment by pka420** [comment]
Just using a standard ubuntu, I already tried different machines. The error still persists with your binaries:

```bash
pka42@cerac-dev-02:~/NBIA_data_retriever_CLI$ ./NBIA_data_retriever_CLI_linux_amd64 -i CMB-AML_October-2023-manifest.tcia -o ./ > output.log
^Cpka42@cerac-dev-02:~/NBIA_data_retriever_CLI$ cat output.log | head
2024-01-03 11:48:49.550 INFO    NBIA_data_retriever_CLI/options.go:87   Using custom meta url: https://services.cancerimagingarchive.net/nbia-api/services/v2/getImage
2024-01-03 11:48:49.550 INFO    NBIA_data_retriever_CLI/token.go:51     restore token from token.json
2024-01-03 11:48:50.365 ERROR   NBIA_data_retriever_CLI/download.go:52  failed to parse response data: invalid character 'P' looking for beginning of value -.#XLICENSE�Vˎ
                                                                                                                                                                          �/� ր4
�M����D��p�6�{f(��3ݓ~H�-����$E��q^��j�d��b�_ۆ]dZ���Iֻ���Vo���7���]Ǎ|'�1[��-e�r�$�+����/�$ڥ4ė�E������.V>l]�-.���

pka42@cerac-dev-02:~/NBIA_data_retriever_CLI$ ./NBIA_data_retriever_CLI -i CMB-AML_October-2023-manifest.tcia -o ./ > output2.log
^Cpka42@cerac-dev-02:~/NBIA_data_retriever_CLI$ cat output2.log | head
2024-01-03 11:49:29.545 INFO    NBIA_data_retriever_CLI/options.go:87   Using custom meta url: https://services.cancerimagingarchive.net/nbia-api/services/v2/getImage
2024-01-03 11:49:29.545 INFO    NBIA_data_retriever_CLI/token.go:51     restore token from token.json
2024-01-03 11:49:30.994 ERROR   NBIA_data_retriever_CLI/download.go:52  failed to parse response data: invalid character 'P' looking for beginning of value -..#XLICENSE�Vˎ
                                                                                                                                                                           �/� ր4
�M����D��p�6�{f(��3ݓ~H�-����$E��q^��j�d��b�_ۆ]dZ���Iֻ���Vo���7���]Ǎ|'�1[��-
```

I don't know why It didn't occur to me that I can save the output to logfile. Just saw this download error.

**Comment by ygidtu** [comment]
Hi, 
   I push a new version to dev branch, the problem should be solved. And I add `--save-log` option, allow you save debug information to `progress.log` under output directory, **Note:** this log file will be overwritten if the output directory is same. 
Please pull the new code and try again.

```bash
cd NBIA_data_retriever_CLI
git checkout dev
git pull
go run . --help
``` 

Best

**Comment by pka420** [comment]
It worked with unrestricted data, and I was able to download the files.
```bash
lucifer@pop-os:~/projects/NBIA_data_retriever_CLI$ go run . -i CMB-AML_October-2023-manifest.tcia -s test/
2024-01-06 12:40:51.050 INFO    NBIA_data_retriever_CLI/token.go:52     restore token from test/token.json

1.3.6.1.4.1.14519.5.2.1.1600.1206.26210688271715166...  45% [==================================================>                                                               ] (25/54 MB, 2.9 MB/s) [25s:10s]^- Ctrl+C pressed in Terminal
```

It worked with unrestricted data as well:
```bash
lucifer@pop-os:~/projects/NBIA_data_retriever_CLI$ go run . -i ./manifest2.tcia -s ./test2 -u some_username -w some_password --save-log 
1.3.6.1.4.1.14519.5.2.1.4219.6651.18269411020515564...  20% [=====================>                                                                                         ] (92/450 MB, 3.4 MB/s) [28s:1m45s]^- Ctrl+C pressed in Terminal
lucifer@pop-os:~/projects/NBIA_data_retriever_CLI$ cat test2/progress.log 
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:06.720","C":"NBIA_data_retriever_CLI/client.go:10","M":"initializing http request client"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:06.720","C":"NBIA_data_retriever_CLI/token.go:49","M":"creating token"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:08.952","C":"NBIA_data_retriever_CLI/token.go:104","M":"saving token to test2/token.json"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:08.952","C":"NBIA_data_retriever_CLI/download.go:17","M":"decoding tcia file: ./manifest2.tcia"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:08.952","C":"NBIA_data_retriever_CLI/download.go:32","M":"tcia file id: 1.3.6.1.4.1.14519.5.2.1.4219.6651.146136900202431607373455344501"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:09.749","C":"NBIA_data_retriever_CLI/download.go:32","M":"tcia file id: 1.3.6.1.4.1.14519.5.2.1.4219.6651.306383459115118250894914293876"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:10.252","C":"NBIA_data_retriever_CLI/download.go:32","M":"tcia file id: 1.3.6.1.4.1.14519.5.2.1.4219.6651.182694110205155645649641184770"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:10.828","C":"NBIA_data_retriever_CLI/download.go:32","M":"tcia file id: 1.3.6.1.4.1.14519.5.2.1.4219.6651.133578453901173938694448827319"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:11.308","C":"NBIA_data_retriever_CLI/download.go:125","M":"getting image file to ./test2"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:36.596","C":"NBIA_data_retriever_CLI/download.go:107","M":"getting meta information and save to ./test2"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:36.596","C":"NBIA_data_retriever_CLI/download.go:125","M":"getting image file to ./test2"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:37.711","C":"NBIA_data_retriever_CLI/download.go:107","M":"getting meta information and save to ./test2"}
{"L":"\u001b[35mDEBUG\u001b[0m","T":"2024-01-06 13:02:37.712","C":"NBIA_data_retriever_CLI/download.go:125","M":"getting image file to ./test2"}
lucifer@pop-os:~/projects/NBIA_data_retriever_CLI$ 
```

so, everything works, and logs are getting saved as well.

**Comment by ygidtu** [comment]
Sonds great, so everything solved？I may   make alittle bit change than release a new version

**Comment by pka420** [comment]
Yes, everything is good. I would like to make a suggestion to the credentials, if it's possible to read them through a file, instead of CLI. 

It is because when we try to run on a cluster machine, every user can read from ps command.

**Comment by ygidtu** [comment]
Do you mean make this a system-wide tool for everyone? You could just put the binary in path like /usr/bin or /usr/local/bin

**Comment by pka420** [comment]
Yee, we already have the binary in a PATH.

But, when lets say admin runs the command to download restricted data, they put in credentials in the command.

The creds can be retrieved using
ps aux | grep tcia

**Comment by ygidtu** [comment]
Hi, I understand now, I'll add a promot or config file to hide the user information

**Comment by ygidtu** [comment]
Hi,
   I make a new release, which add new argument `-w` allow you input password interactively. And rename `token.json` to `username.json`, which make sure multiple users could download to same output directory at same time
Best
