### ISSUE TITLE
Retry failed download or export them for another try

### ISSUE THREAD

**Issue by linhandev** [ygidtu/NBIA_data_retriever_CLI#6]
Hi, I have been using this great tool for some time and have a question about failed download.
Cuz I am using this program behind proxy, from time to time there will be failed downloads. Is it possible to retry those failed files or export the patients to download another time?

**Comment by linhandev** [comment]
Those error mostly happen when I do multi process download behind proxy, reducing -p will reduce error rate but it would be convenient to export those failed downloads and retry them.

**Comment by ygidtu** [comment]
I use a json file to log the download progress, and  skip the  logged records next time.
I already noticed that some files  corrupted while downlaoding, I maybed try to fix this recently.

You just re-run your command line, the  downloaded file should be skipped. 
If there are some files still corruped, just delte the corresponding json file and re-run the code

**Comment by linhandev** [comment]
Sorry for the late reply. I didn't notice this behavior while running but it sounds really useful. I will try to rerun it and see what happens. Many thanks for this great tool!
