### ISSUE TITLE
Skip restricted data

### ISSUE THREAD

**Issue by linhandev** [ygidtu/NBIA_data_retriever_CLI#7]
Hi, thanks for this great tool.
I have been downloading data recently and encountered some restricted data. Would u be so kind to consider adding a " skip restricted data" option? I think this may not be too hard to implement but I don't really know golang. 
Thanks!

**Comment by linhandev** [comment]
Or is this function already included? I noticed an error during download saying things about username and password, but I now think maybe it's caused by errors in multi process downloading.

**Comment by ygidtu** [comment]
Can you provide a small example? I'm no so clear how to process this error is more appropriate. Just single restricted record in ncia file is enough

**Comment by ygidtu** [comment]
I release a new beta version without  testing, it might work, please try

**Comment by linhandev** [comment]
Sorry for the late reply, I don't check GitHub messages too often. Thank u so much for making the modification. Will try it out today!

**Comment by linhandev** [comment]
I have tried on the data I previously failed to download, and believe it works wonderfully, at least for the list I tried on. Many thanks!
