### ISSUE TITLE
Is this available for Ubuntu?

### ISSUE THREAD

**Issue by super233** [ygidtu/NBIA_data_retriever_CLI#8]
Is this available for Ubuntu?

**Comment by emma-sjwang** [comment]
why close this issue?
Is it available for Ubuntu?

**Comment by ygidtu** [comment]
Of course, please use the linux_adm64 version. Or you could build from souce with Go

**Comment by emma-sjwang** [comment]
Ok. Thank you so much.
Your repo really saved my life.

**Comment by dirtycomputer** [comment]
Is this available for Ubuntu x86?

**Comment by ygidtu** [comment]
Please try with this version. I didn't build for x86 platform by default.
[NBIA_data_retriever_CLI_linux_386.zip](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/14046034/NBIA_data_retriever_CLI_linux_386.zip)
