### ISSUE TITLE
BUG: Run time Error

### ISSUE THREAD

**Issue by pka420** [ygidtu/NBIA_data_retriever_CLI#9]
Hi, I am getting a runtime error while downloading data.
![image](https://user-images.githubusercontent.com/30459586/125387438-c82abe80-e352-11eb-8dfe-d123fed66321.png)

I am calling the script like this:
        `nbia_cli_linux_amd64 -i ${manifest_file} -o ${download_location}/  -t 172800000000 -p 1 &>> \ 
    $tmp_root/nbia_data_retriever_cli.log`
[error_discuss.log](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/6806589/error_discuss.log)

**Comment by ygidtu** [comment]
Could provide the link in your example ?

**Comment by pka420** [comment]
> Could provide the link in your example ?

Hmm, link to the image?

**Comment by ygidtu** [comment]
sorry. link in the image. I need check this link and detailed error mesaage ---- Replied Message ----FromPiyush ***@***.***>Date07/13/2021 14:56 ***@***.***> ***@***.******@***.***>SubjectRe: [ygidtu/NBIA_data_retriever_CLI] BUG: Run time Error (#9)

Could provide the link in your example ?

Hmm, link to the image?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ygidtu/NBIA_data_retriever_CLI/issues/9#issuecomment-878829133",
"url": "https://github.com/ygidtu/NBIA_data_retriever_CLI/issues/9#issuecomment-878829133",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Javes7777** [comment]
> sorry. link in the image. I need check this link and detailed error mesaage ---- Replied Message ----FromPiyush ***@***.***>Date07/13/2021 14:56 ***@***.***> ***@***.******@***.***>SubjectRe: [ygidtu/NBIA_data_retriever_CLI] BUG: Run time Error (#9) Could provide the link in your example ? Hmm, link to the image? —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#9 (comment)](https://github.com/ygidtu/NBIA_data_retriever_CLI/issues/9#issuecomment-878829133)", "url": "[#9 (comment)](https://github.com/ygidtu/NBIA_data_retriever_CLI/issues/9#issuecomment-878829133)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by pka420** [comment]
I attached the log file, `error_discuss.log` in my first comment. 
Sorry, I accidentally closed the issue, reopened it again.

**Comment by ygidtu** [comment]
I run a several tests on `https://public.cancerimagingarchive.net/nbia-download/servlet/DownloadServletV3?numberOfSeries=1&series1=1.2.276.0.7230010.3.1.3.8323329.16721.1440002299.978656`, every thing seems fine. Could you clone my latest code and run `go test` to check it out?

![image](https://user-images.githubusercontent.com/29178828/125412993-02976880-e3f2-11eb-8bf0-55e1cb65794d.png)

**Comment by pka420** [comment]
Hi, I cloned the repo and ran `go test` and got the same output as you. Not sure what it signifies though? 

Ran the script again with the same manifest file, but I ran into another error, please look at the end of this file: 
[nbia_data_retriever_cli.log](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/6811471/nbia_data_retriever_cli.log)

The manifest file used: 
[manifest.txt](https://github.com/ygidtu/NBIA_data_retriever_CLI/files/6812001/manifest.txt)

**Comment by ygidtu** [comment]
According to the log it shoud be an network issue, could you try to use any proxy? Or just run this command until it succeesd, this program should automatically resume from last time.

![image](https://user-images.githubusercontent.com/29178828/125548403-128c570f-315b-4e2b-9229-88561aff30e4.png)
Either the domain name cannot be resolved locally, or the download limit of the server is encountered

**Comment by pka420** [comment]
Thanks for your insight. No, I did not use any proxy. I can try using proxy and see.
Yes, I can run this program until it eventually succeeds. But, it would be nice to have not to run it again and again.

**Comment by ygidtu** [comment]
Yeah, the network issue is quiet annoying. I will try to add a function that will automatically retry after waiting for a period of time, which may help
